/**
 * Demo Configuration & Fallback Datasets
 * Ensures full UI interactivity and vibrant images even during offline/standalone demo testing.
 */

export const DEMO_USERS = {
  customer: {
    email: import.meta.env.VITE_DEMO_CUSTOMER_EMAIL || 'customer@quickcart.com',
    password: import.meta.env.VITE_DEMO_CUSTOMER_PASSWORD || 'Customer@123',
    role: 'ROLE_CUSTOMER',
    label: 'Customer',
  },
  driver: {
    email: import.meta.env.VITE_DEMO_DRIVER_EMAIL || 'driver@quickcart.com',
    password: import.meta.env.VITE_DEMO_DRIVER_PASSWORD || 'Driver@123',
    role: 'ROLE_DELIVERY_PARTNER',
    label: 'Delivery Partner',
  },
  admin: {
    email: import.meta.env.VITE_DEMO_ADMIN_EMAIL || 'admin@quickcart.com',
    password: import.meta.env.VITE_DEMO_ADMIN_PASSWORD || 'Admin@123',
    role: 'ROLE_ADMIN',
    label: 'Admin',
  },
};

export const getDemoCredentials = (roleKey) => {
  return DEMO_USERS[roleKey] || null;
};

export const FALLBACK_CATEGORIES = [
  {
    id: 1,
    name: 'Fruits & Vegetables',
    slug: 'fruits-vegetables',
    imageUrl:
      'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=400&auto=format&fit=crop&q=80',
    description: 'Fresh farm fruits, leafy greens & organic vegetables',
  },
  {
    id: 2,
    name: 'Dairy, Bread & Eggs',
    slug: 'dairy-bread-eggs',
    imageUrl:
      'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&auto=format&fit=crop&q=80',
    description: 'Fresh milk, farm eggs, artisanal butter & bread',
  },
  {
    id: 3,
    name: 'Snacks & Munchies',
    slug: 'snacks-munchies',
    imageUrl:
      'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400&auto=format&fit=crop&q=80',
    description: 'Crisps, nachos, popcorn & roasted namkeen',
  },
  {
    id: 4,
    name: 'Cold Drinks & Juices',
    slug: 'cold-drinks-juices',
    imageUrl:
      'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&auto=format&fit=crop&q=80',
    description: 'Refreshing sodas, iced teas, organic smoothies & cold brew',
  },
  {
    id: 5,
    name: 'Instant & Frozen Food',
    slug: 'instant-frozen',
    imageUrl:
      'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&auto=format&fit=crop&q=80',
    description: 'Ramen noodles, frozen momos, ready meals & pasta',
  },
  {
    id: 6,
    name: 'Bakery & Biscuits',
    slug: 'bakery-biscuits',
    imageUrl:
      'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&auto=format&fit=crop&q=80',
    description: 'Croissants, cookies, sourdough loaves & cakes',
  },
  {
    id: 7,
    name: 'Sweet Tooth & Ice Creams',
    slug: 'sweet-tooth',
    imageUrl:
      'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=400&auto=format&fit=crop&q=80',
    description: 'Artisanal chocolates, gelato tubs & desserts',
  },
  {
    id: 8,
    name: 'Tea, Coffee & Health Drinks',
    slug: 'tea-coffee',
    imageUrl:
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400&auto=format&fit=crop&q=80',
    description: 'Specialty coffee beans, green matcha & chai blends',
  },
  {
    id: 9,
    name: 'Clothes & Fashion',
    slug: 'clothes-fashion',
    imageUrl:
      'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=400&auto=format&fit=crop&q=80',
    description: 'Premium t-shirts, shirts, denim jeans, cotton hoodies, kurtas & dresses',
  },
];

export const FALLBACK_CLOTHES = [
  {
    id: 301,
    name: 'Classic Crewneck Cotton T-Shirt',
    slug: 'classic-crewneck-cotton-tshirt',
    brand: 'Roadster',
    department: 'Men',
    garmentType: 'T-Shirts',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Jet Black', 'Navy Blue', 'Heather Grey', 'Pure White'],
    fabric: '100% Pre-Shrunk Combed Cotton (180 GSM)',
    fit: 'Regular Fit',
    unitQuantity: 'Sizes: S, M, L, XL, XXL',
    sellingPrice: 399,
    price: 399,
    mrp: 799,
    discountPercentage: 50,
    rating: 4.8,
    reviewCount: 185,
    isFeatured: true,
    isDeal: true,
    categoryId: 9,
    categorySlug: 'clothes-fashion',
    inStock: true,
    stockQuantity: 60,
    imageUrl:
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&auto=format&fit=crop&q=80',
    ],
    description:
      'Ultra-soft, breathable everyday crewneck t-shirt made with 100% premium combed cotton with bio-washed finish.',
  },
  {
    id: 302,
    name: 'Slim Fit Stretch Denim Jeans',
    slug: 'slim-fit-stretch-denim-jeans',
    brand: "Levi's",
    department: 'Men',
    garmentType: 'Jeans',
    sizes: ['30', '32', '34', '36'],
    colors: ['Indigo Dark Wash', 'Faded Blue', 'Midnight Black'],
    fabric: '99% Organic Cotton, 1% Elastane Stretch Denim',
    fit: 'Slim Fit',
    unitQuantity: 'Sizes: 30, 32, 34, 36',
    sellingPrice: 1599,
    price: 1599,
    mrp: 2799,
    discountPercentage: 43,
    rating: 4.9,
    reviewCount: 240,
    isFeatured: true,
    isDeal: false,
    categoryId: 9,
    categorySlug: 'clothes-fashion',
    inStock: true,
    stockQuantity: 40,
    imageUrl:
      'https://images.unsplash.com/photo-1542272604-780c96856592?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1542272604-780c96856592?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&auto=format&fit=crop&q=80',
    ],
    description:
      'Iconic slim fit stretch jeans offering flexible movement, authentic wash effects, and durable 5-pocket styling.',
  },
  {
    id: 303,
    name: 'Oxford Casual Button-Down Shirt',
    slug: 'oxford-casual-buttondown-shirt',
    brand: 'Allen Solly',
    department: 'Men',
    garmentType: 'Shirts',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Pastel Sky Blue', 'Crisp White', 'Soft Olive'],
    fabric: '100% Premium Breathable Cotton',
    fit: 'Modern Tailored Fit',
    unitQuantity: 'Sizes: M, L, XL, XXL',
    sellingPrice: 899,
    price: 899,
    mrp: 1699,
    discountPercentage: 47,
    rating: 4.7,
    reviewCount: 130,
    isFeatured: true,
    isDeal: true,
    categoryId: 9,
    categorySlug: 'clothes-fashion',
    inStock: true,
    stockQuantity: 45,
    imageUrl:
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80',
    ],
    description:
      'Sophisticated Oxford weave button-down shirt ideal for effortless smart-casual layering and all-day office comfort.',
  },
  {
    id: 304,
    name: 'Floral Print Summer Cotton Midi Dress',
    slug: 'floral-print-summer-midi-dress',
    brand: 'H&M',
    department: 'Women',
    garmentType: 'Dresses',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Floral Sage Green', 'Blush Rose', 'Sunflower Yellow'],
    fabric: '100% Breathable Lightweight Viscose Cotton',
    fit: 'A-Line Flowy Fit',
    unitQuantity: 'Sizes: XS, S, M, L, XL',
    sellingPrice: 999,
    price: 999,
    mrp: 1999,
    discountPercentage: 50,
    rating: 4.8,
    reviewCount: 115,
    isFeatured: true,
    isDeal: true,
    categoryId: 9,
    categorySlug: 'clothes-fashion',
    inStock: true,
    stockQuantity: 35,
    imageUrl:
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&auto=format&fit=crop&q=80',
    ],
    description:
      'Charming tiered floral midi dress with sweetheart neckline, smocked back, and fluttering cap sleeves.',
  },
  {
    id: 305,
    name: 'Dry-Fit Athletic Training T-Shirt',
    slug: 'dryfit-athletic-training-tshirt',
    brand: 'Nike',
    department: 'Unisex',
    garmentType: 'Activewear',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Obsidian Black', 'Volt Green', 'Royal Crimson'],
    fabric: 'Moisture-Wicking Dri-FIT Poly Mesh',
    fit: 'Athletic Athletic Fit',
    unitQuantity: 'Sizes: S, M, L, XL, XXL',
    sellingPrice: 899,
    price: 899,
    mrp: 1495,
    discountPercentage: 40,
    rating: 4.8,
    reviewCount: 210,
    isFeatured: true,
    isDeal: false,
    categoryId: 9,
    categorySlug: 'clothes-fashion',
    inStock: true,
    stockQuantity: 50,
    imageUrl:
      'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800&auto=format&fit=crop&q=80',
    ],
    description:
      'High-performance quick-drying workout top engineered for high-intensity training, running, and athletic agility.',
  },
  {
    id: 306,
    name: 'Cozy Fleece Pullover Winter Hoodie',
    slug: 'cozy-fleece-pullover-hoodie',
    brand: 'Zara Man',
    department: 'Unisex',
    garmentType: 'Hoodies',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Charcoal Heather', 'Oatmeal Beige', 'Dusty Olive'],
    fabric: '360 GSM Cotton-Poly Heavyweight Fleece',
    fit: 'Relaxed Drop-Shoulder Fit',
    unitQuantity: 'Sizes: M, L, XL, XXL',
    sellingPrice: 1349,
    price: 1349,
    mrp: 2499,
    discountPercentage: 46,
    rating: 4.7,
    reviewCount: 95,
    isFeatured: false,
    isDeal: true,
    categoryId: 9,
    categorySlug: 'clothes-fashion',
    inStock: true,
    stockQuantity: 30,
    imageUrl:
      'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80',
    ],
    description:
      'Super-warm brushed interior fleece hoodie featuring double-layer hood, matching drawstrings, and kangaroo hand pocket.',
  },
  {
    id: 307,
    name: 'Handcrafted Silk Blend Festive Kurta',
    slug: 'handcrafted-silk-blend-kurta',
    brand: 'FabIndia',
    department: 'Men',
    garmentType: 'Ethnic Wear',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Royal Mustard', 'Maroon Wine', 'Ivory Cream'],
    fabric: 'Chanderi Silk-Cotton Blend',
    fit: 'Classic Straight Fit',
    unitQuantity: 'Sizes: S, M, L, XL',
    sellingPrice: 1299,
    price: 1299,
    mrp: 2290,
    discountPercentage: 43,
    rating: 4.6,
    reviewCount: 78,
    isFeatured: false,
    isDeal: false,
    categoryId: 9,
    categorySlug: 'clothes-fashion',
    inStock: true,
    stockQuantity: 25,
    imageUrl:
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80',
    ],
    description:
      'Artisanal festive ethnic kurta with delicate thread work along the mandarin placket, perfect for celebrations.',
  },
  {
    id: 308,
    name: 'Tailored Stretch Chino Trousers',
    slug: 'tailored-stretch-chino-trousers',
    brand: 'Van Heusen',
    department: 'Men',
    garmentType: 'Trousers',
    sizes: ['30', '32', '34', '36'],
    colors: ['Classic Khaki', 'Slate Grey', 'Navy Blue'],
    fabric: '98% Cotton Twill, 2% Spandex',
    fit: 'Tapered Regular Fit',
    unitQuantity: 'Sizes: 30, 32, 34, 36',
    sellingPrice: 1099,
    price: 1099,
    mrp: 1899,
    discountPercentage: 42,
    rating: 4.7,
    reviewCount: 86,
    isFeatured: true,
    isDeal: false,
    categoryId: 9,
    categorySlug: 'clothes-fashion',
    inStock: true,
    stockQuantity: 40,
    imageUrl:
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&auto=format&fit=crop&q=80',
    ],
    description:
      'Versatile stretch cotton chino trousers tailored with clean flat fronts, slant pockets, and wrinkle-resistant finish.',
  },
];

export const FALLBACK_PRODUCTS = [
  {
    id: 101,
    name: 'Fresh Organic Hass Avocados',
    slug: 'fresh-organic-hass-avocados',
    brand: 'FreshFarm',
    unitQuantity: '2 pcs (approx. 350g)',
    sellingPrice: 160,
    price: 160,
    mrp: 220,
    discountPercentage: 27,
    rating: 4.9,
    ratingCount: 230,
    reviewCount: 230,
    isFeatured: true,
    isDeal: true,
    categoryId: 1,
    categorySlug: 'fruits-vegetables',
    inStock: true,
    stockQuantity: 45,
    imageUrl:
      'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=500&auto=format&fit=crop&q=80',
    description:
      'Buttery, rich, premium Hass avocados loaded with healthy fats and essential minerals.',
  },
  {
    id: 102,
    name: 'Amul Taaza Homogenised Toned Milk',
    slug: 'amul-taaza-toned-milk',
    brand: 'Amul',
    unitQuantity: '1 Litre Tetra Pak',
    sellingPrice: 74,
    price: 74,
    mrp: 80,
    discountPercentage: 8,
    rating: 4.8,
    ratingCount: 1450,
    reviewCount: 1450,
    isFeatured: true,
    isDeal: false,
    categoryId: 2,
    categorySlug: 'dairy-bread-eggs',
    inStock: true,
    stockQuantity: 120,
    imageUrl:
      'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&auto=format&fit=crop&q=80',
    description: 'Pure, pasteurized, homogenized toned fresh milk with 3.0% milk fat.',
  },
  {
    id: 103,
    name: 'Fresh English English Sourdough Bread',
    slug: 'fresh-sourdough-bread',
    brand: 'The Baker’s Guild',
    unitQuantity: '400g Loaf',
    sellingPrice: 95,
    price: 95,
    mrp: 120,
    discountPercentage: 21,
    rating: 4.7,
    ratingCount: 310,
    reviewCount: 310,
    isFeatured: true,
    isDeal: true,
    categoryId: 2,
    categorySlug: 'dairy-bread-eggs',
    inStock: true,
    stockQuantity: 28,
    imageUrl:
      'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80',
    description:
      'Artisanal naturally fermented sourdough loaf baked with stone-ground flour and crispy crust.',
  },
  {
    id: 104,
    name: 'Kashmiri Sweet Red Apples',
    slug: 'kashmiri-sweet-red-apples',
    brand: 'Valley Fresh',
    unitQuantity: '4 pcs (approx. 600g)',
    sellingPrice: 140,
    price: 140,
    mrp: 180,
    discountPercentage: 22,
    rating: 4.8,
    ratingCount: 680,
    reviewCount: 680,
    isFeatured: true,
    isDeal: true,
    categoryId: 1,
    categorySlug: 'fruits-vegetables',
    inStock: true,
    stockQuantity: 60,
    imageUrl:
      'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=500&auto=format&fit=crop&q=80',
    description:
      'Crisp, aromatic, and sweet organic apples freshly harvested from Kashmir orchards.',
  },
  {
    id: 105,
    name: 'Epigamia Greek Yogurt Natural Blueberry',
    slug: 'epigamia-greek-yogurt-blueberry',
    brand: 'Epigamia',
    unitQuantity: '120g Cup',
    sellingPrice: 60,
    price: 60,
    mrp: 70,
    discountPercentage: 14,
    rating: 4.9,
    ratingCount: 420,
    reviewCount: 420,
    isFeatured: true,
    isDeal: false,
    categoryId: 2,
    categorySlug: 'dairy-bread-eggs',
    inStock: true,
    stockQuantity: 50,
    imageUrl:
      'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500&auto=format&fit=crop&q=80',
    description:
      'High-protein, preservative-free Greek yogurt blended with wild real blueberry pulp.',
  },
  {
    id: 106,
    name: 'Doritos Sweet Chilli Nachos Mega Pack',
    slug: 'doritos-sweet-chilli-nachos',
    brand: 'Doritos',
    unitQuantity: '150g Pack',
    sellingPrice: 50,
    price: 50,
    mrp: 60,
    discountPercentage: 17,
    rating: 4.6,
    ratingCount: 920,
    reviewCount: 920,
    isFeatured: false,
    isDeal: true,
    categoryId: 3,
    categorySlug: 'snacks-munchies',
    inStock: true,
    stockQuantity: 85,
    imageUrl:
      'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=80',
    description: 'Crunchy triangle corn tortilla chips seasoned with zesty sweet chilli spices.',
  },
  {
    id: 107,
    name: 'Coca-Cola Zero Sugar Chilled Can',
    slug: 'coca-cola-zero-sugar-can',
    brand: 'Coca-Cola',
    unitQuantity: '300ml Can',
    sellingPrice: 40,
    price: 40,
    mrp: 40,
    discountPercentage: 0,
    rating: 4.8,
    ratingCount: 2100,
    reviewCount: 2100,
    isFeatured: true,
    isDeal: false,
    categoryId: 4,
    categorySlug: 'cold-drinks-juices',
    inStock: true,
    stockQuantity: 150,
    imageUrl:
      'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80',
    description: 'Zero calorie, zero sugar crisp sparkling cola taste served ice cold.',
  },
  {
    id: 108,
    name: 'Lindt Excellence 85% Cocoa Dark Chocolate',
    slug: 'lindt-excellence-dark-chocolate',
    brand: 'Lindt',
    unitQuantity: '100g Bar',
    sellingPrice: 275,
    price: 275,
    mrp: 325,
    discountPercentage: 15,
    rating: 4.9,
    ratingCount: 780,
    reviewCount: 780,
    isFeatured: true,
    isDeal: true,
    categoryId: 7,
    categorySlug: 'sweet-tooth',
    inStock: true,
    stockQuantity: 35,
    imageUrl:
      'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=500&auto=format&fit=crop&q=80',
    description:
      'Master Swiss chocolatier crafted intense, smooth dark chocolate with robust roasted cocoa notes.',
  },
];

export const FALLBACK_RESTAURANTS = [
  {
    id: 1,
    name: 'Trattoria da Enzo al 29',
    slug: 'trattoria-da-enzo-rome',
    description:
      'Authentic Roman trattoria renowned for signature Carbonara, Cacio e Pepe, and fresh burrata.',
    cuisine: 'Italian',
    country: 'Italy',
    city: 'Rome',
    address: 'Via dei Vascellari, 29, 00153 Roma RM',
    latitude: 41.8885,
    longitude: 12.4764,
    rating: 4.9,
    reviewCount: 340,
    priceLevel: '$$',
    imageUrl:
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=60',
    galleryImages: [
      'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800&auto=format&fit=crop&q=60',
      'https://images.unsplash.com/photo-1579684947550-22e945225d9a?w=800&auto=format&fit=crop&q=60',
    ],
    openingHours: '12:30 PM - 11:00 PM',
    phone: '+39 06 581 2260',
    website: 'https://trattoriadaenzo.it',
    isVegetarianFriendly: true,
    isVeganFriendly: false,
    isDineInAvailable: true,
    isFavorite: false,
  },
  {
    id: 2,
    name: 'Sukiyabashi Jiro Roppongi',
    slug: 'sukiyabashi-jiro-tokyo',
    description:
      'World-class Edomae sushi experience crafted with meticulously selected seasonal seafood.',
    cuisine: 'Japanese',
    country: 'Japan',
    city: 'Tokyo',
    address: 'Roppongi Hills Keyakizaka Dori 3F, Minato-ku, Tokyo',
    latitude: 35.6596,
    longitude: 139.7297,
    rating: 4.95,
    reviewCount: 520,
    priceLevel: '$$$$',
    imageUrl:
      'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&auto=format&fit=crop&q=60',
    galleryImages: [
      'https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=800&auto=format&fit=crop&q=60',
    ],
    openingHours: '11:30 AM - 9:30 PM',
    phone: '+81 3-5413-6626',
    website: 'https://sushi-jiro.jp',
    isVegetarianFriendly: false,
    isVeganFriendly: false,
    isDineInAvailable: true,
    isFavorite: false,
  },
  {
    id: 3,
    name: 'Gramercy Tavern',
    slug: 'gramercy-tavern-new-york',
    description:
      'Contemporary American culinary staple featuring wood-fired seasonal dining and farm-to-table menus.',
    cuisine: 'American',
    country: 'USA',
    city: 'New York',
    address: '42 E 20th St, New York, NY 10003',
    latitude: 40.7384,
    longitude: -73.9884,
    rating: 4.8,
    reviewCount: 410,
    priceLevel: '$$$',
    imageUrl:
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=60',
    galleryImages: [
      'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=60',
    ],
    openingHours: '12:00 PM - 10:00 PM',
    phone: '+1 212-477-0777',
    website: 'https://gramercytavern.com',
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isDineInAvailable: true,
    isFavorite: false,
  },
  {
    id: 4,
    name: 'Dishoom Shoreditch',
    slug: 'dishoom-shoreditch-london',
    description:
      'Paying homage to the heritage Irani cafes of Bombay with signature black daal and gunpowder potatoes.',
    cuisine: 'Indian',
    country: 'UK',
    city: 'London',
    address: '7 Boundary St, London E2 7JE',
    latitude: 51.5244,
    longitude: -0.0772,
    rating: 4.85,
    reviewCount: 680,
    priceLevel: '$$',
    imageUrl:
      'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&auto=format&fit=crop&q=60',
    galleryImages: [],
    openingHours: '8:00 AM - 11:00 PM',
    phone: '+44 20 7420 9324',
    website: 'https://dishoom.com',
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isDineInAvailable: true,
    isFavorite: false,
  },
  {
    id: 5,
    name: 'Toscano Italian Bistro & Wine Bar',
    slug: 'toscano-ub-city-bengaluru',
    description:
      'Charming open-air Italian restaurant and wine bar overlooking UB City amphitheatre.',
    cuisine: 'Italian',
    country: 'India',
    city: 'Bengaluru',
    address: 'UB City, Vittal Mallya Rd, Bengaluru, Karnataka 560001',
    latitude: 12.9719,
    longitude: 77.596,
    rating: 4.75,
    reviewCount: 380,
    priceLevel: '$$$',
    imageUrl:
      'https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?w=800&auto=format&fit=crop&q=60',
    galleryImages: [],
    openingHours: '11:00 AM - 11:00 PM',
    phone: '+91 80 4173 8800',
    website: 'https://toscano.co.in',
    isVegetarianFriendly: true,
    isVeganFriendly: true,
    isDineInAvailable: true,
    isFavorite: false,
  },
];
